######################################################################
# Automatically generated by qmake (2.01a) Thu 4. Aug 21:38:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

win32:RC_FILE += ForbidSleepingMode.rc